#!/bin/sh

set -eux

os="${1:-fedora}"
cd "${0%/*}"

../common/check-config

case "${os}" in
    fedora)
        containerfile='Containerfile'
        features='--features=pre-6.15'
        ;;
    arch)
        containerfile='Containerfile.arch'
        features='--features=pre-6.15'
        ;;
    rhel9)
        containerfile='Containerfile.rhel9'
        features='--features=rhel9'
        ;;
    ubuntu)
        containerfile='Containerfile.ubuntu'
        features='--features=pre-6.15'
        ;;
    rawhide)
        containerfile='Containerfile.rawhide'
        features='--no-default-features'
        ;;
    *)
        echo "*** unknown variant ${os}"
        false
        ;;
esac

cargo build --release "${features}"

cp ../../target/release/cfsctl .
cp ../../target/release/composefs-setup-root extra/usr/lib/dracut/modules.d/37composefs/
CFSCTL='./cfsctl --repo tmp/sysroot/composefs'

rm -rf tmp
mkdir -p tmp/sysroot/composefs

podman build \
    --iidfile=tmp/base.iid \
    -f "${containerfile}" \
    .

BASE_ID="$(sed s/sha256:// tmp/base.iid)"

${CFSCTL} oci pull containers-storage:${BASE_ID}
${CFSCTL} oci prepare-boot "${BASE_ID}" --bootdir tmp/efi --cmdline console=ttyS0,115200 --entry-id=example --cmdline rw

../common/install-systemd-boot
../common/make-image "${os}-bls-efi.qcow2"
