#!/bin/sh

set -eux

cd "${0%/*}"

# https://github.com/containers/buildah/issues/5656
PODMAN_BUILD="podman build --no-cache"

cargo build --release

cp ../../target/release/cfsctl .
cp ../../target/release/composefs-pivot-sysroot extra/usr/lib/dracut/modules.d/37composefs/
CFSCTL='./cfsctl --repo tmp/sysroot/composefs'

rm -rf tmp
mkdir -p tmp/sysroot/composefs tmp/sysroot/var

${PODMAN_BUILD} \
    --iidfile=tmp/base.iid \
    "$@" \
    .

BASE_ID="$(sed s/sha256:// tmp/base.iid)"
podman save --format oci-archive -o tmp/base.tar "${BASE_ID}"
${CFSCTL} oci pull oci-archive:tmp/base.tar
BASE_IMAGE_FSVERITY="$(${CFSCTL} oci create-image "${BASE_ID}")"

mkdir -p tmp/efi/loader
echo 'timeout 3' > tmp/efi/loader/loader.conf
mkdir -p tmp/efi/EFI/BOOT tmp/efi/EFI/systemd
cp /usr/lib/systemd/boot/efi/systemd-bootx64.efi tmp/efi/EFI/systemd
cp /usr/lib/systemd/boot/efi/systemd-bootx64.efi tmp/efi/EFI/BOOT/BOOTX64.EFI
${CFSCTL} oci prepare-boot "${BASE_ID}" tmp/efi

BLE="$(echo tmp/efi/loader/entries/*.conf)"
test -f "${BLE}"
if grep '^options ' "${BLE}"; then
    sed -i "s/^options .*$/\0 composefs=${BASE_IMAGE_FSVERITY} rw/" "${BLE}"
else
    echo "options    composefs=${BASE_IMAGE_FSVERITY} rw" >> "${BLE}"
fi
sed -i 's@ /boot/@ /@' "${BLE}"

../common/make-image image.qcow2
