FROM fedora:rawhide
COPY extra /
RUN --mount=type=cache,target=/var/cache/libdnf5 <<EOF
    set -eux

    dnf --setopt keepcache=1 install --allowerasing -y \
        composefs \
        dosfstools \
        kernel \
        openssh-server \
        skopeo \
        strace \
        systemd \
        util-linux

    systemctl enable systemd-networkd
    passwd -d root
    mkdir /sysroot
EOF
COPY cfsctl /usr/bin
