# A special form of Containerfile for composefs-enabled UKI images
# This file must have:
#
#  - a stage called 'base' which contains all of the
#    files of the final image, but not the kernel
#
#  - further stages, ultimately resulting in the final container image.  In
#    this image, the kernel must be present in a whiteout-obscured directory
#    /composefs-meta/boot/ and otherwise no other changes may be made vs. the
#    base image.  This is best-accomplished with a multi-stage build.
#
#  - during the build stages following 'base', the `COMPOSEFS_FSVERITY` build
#    arg will be set to the fsverity digest of the container image.  This should
#    be baked into the UKI.

# Need 6.12 kernel from rawhide
FROM fedora:rawhide AS base
COPY extra /
COPY cfsctl /usr/bin
RUN <<EOF
    set -eux
    dnf --setopt keepcache=1 install -y systemd util-linux skopeo composefs strace dosfstools kernel
    systemctl enable systemd-networkd
    passwd -d root
    mkdir /sysroot
    mkdir /composefs-meta
    mv /boot /composefs-meta
    mkdir /boot
EOF
RUN true
