#!/bin/sh

set -eux

cd "${0%/*}"

# https://github.com/containers/buildah/issues/5656
PODMAN_BUILD="podman build --no-cache"

cargo build --release

cp ../../target/release/cfsctl .
cp ../../target/release/composefs-pivot-sysroot extra/usr/lib/dracut/modules.d/37composefs/
CFSCTL='./cfsctl --repo tmp/sysroot/composefs'

rm -rf tmp
mkdir -p tmp/sysroot/composefs tmp/sysroot/var

${PODMAN_BUILD} \
    --iidfile=tmp/base.iid \
    --target=base \
    "$@" \
    .

BASE_ID="$(sed s/sha256:// tmp/base.iid)"
podman save --format oci-archive -o tmp/base.tar "${BASE_ID}"
${CFSCTL} oci pull oci-archive:tmp/base.tar
BASE_IMAGE_FSVERITY="$(${CFSCTL} oci create-image "${BASE_ID}")"

${PODMAN_BUILD} \
    --iidfile=tmp/final.iid \
    --build-context=base="container-image://${BASE_ID}" \
    --build-arg=COMPOSEFS_FSVERITY="${BASE_IMAGE_FSVERITY}" \
    --label=containers.composefs.fsverity="${BASE_IMAGE_FSVERITY}" \
    "$@" \
    .

FINAL_ID="$(sed s/sha256:// tmp/final.iid)"
podman save --format oci-archive -o tmp/final.tar "${FINAL_ID}"
${CFSCTL} oci pull oci-archive:tmp/final.tar
FINAL_IMAGE_FSVERITY="$(${CFSCTL} oci create-image "${FINAL_ID}")"

## IMPORTANT: the filesystems of the base and final images are identical
test "${BASE_IMAGE_FSVERITY}" = "${FINAL_IMAGE_FSVERITY}"

mkdir -p tmp/efi/loader
echo 'timeout 3' > tmp/efi/loader/loader.conf
mkdir -p tmp/efi/EFI/BOOT tmp/efi/EFI/systemd
cp /usr/lib/systemd/boot/efi/systemd-bootx64.efi tmp/efi/EFI/systemd
cp /usr/lib/systemd/boot/efi/systemd-bootx64.efi tmp/efi/EFI/BOOT/BOOTX64.EFI
${CFSCTL} oci prepare-boot "${FINAL_ID}" tmp/efi

fakeroot ./make-image
qemu-img convert -f raw tmp/image.raw -O qcow2 image.qcow2
./fix-verity image.qcow2  # https://github.com/tytso/e2fsprogs/issues/201
