#!/bin/sh

set -eux

os="${1:-fedora}"
cd "${0%/*}"

../common/check-config

case "${os}" in
    fedora)
        containerfile='Containerfile'
        features='--features=pre-6.15'
        ;;
    arch)
        containerfile='Containerfile.arch'
        features='--features=pre-6.15'
        ;;
    *)
        echo "*** unknown variant ${os}"
        false
        ;;
esac

# https://github.com/containers/buildah/issues/5656
PODMAN_BUILD="podman build --no-cache"

cargo build --release "${features}"

cp ../../target/release/cfsctl .
cp ../../target/release/composefs-setup-root extra/usr/lib/dracut/modules.d/37composefs/
CFSCTL='./cfsctl --repo tmp/sysroot/composefs'

rm -rf tmp
mkdir -p tmp/sysroot/composefs

${PODMAN_BUILD} \
    --iidfile=tmp/base.iid \
    --target=base \
    -f "${containerfile}" \
    .

BASE_ID="$(sed s/sha256:// tmp/base.iid)"
${CFSCTL} oci pull containers-storage:"${BASE_ID}"
BASE_IMAGE_FSVERITY="$(${CFSCTL} oci create-image "${BASE_ID}")"

${PODMAN_BUILD} \
    --iidfile=tmp/final.iid \
    --build-context=base="container-image://${BASE_ID}" \
    --build-arg=COMPOSEFS_FSVERITY="${BASE_IMAGE_FSVERITY}" \
    --label=containers.composefs.fsverity="${BASE_IMAGE_FSVERITY}" \
    -f "${containerfile}" \
    .

FINAL_ID="$(sed s/sha256:// tmp/final.iid)"
${CFSCTL} oci pull containers-storage:"${FINAL_ID}"
FINAL_IMAGE_FSVERITY="$(${CFSCTL} oci create-image "${FINAL_ID}")"
fsck.erofs "tmp/sysroot/composefs/images/${FINAL_IMAGE_FSVERITY}"

## IMPORTANT: the filesystems of the base and final images are identical
test "${BASE_IMAGE_FSVERITY}" = "${FINAL_IMAGE_FSVERITY}"

mkdir -p "tmp/sysroot/state/${BASE_IMAGE_FSVERITY}/etc/work"
mkdir -p "tmp/sysroot/state/${BASE_IMAGE_FSVERITY}/etc/upper"
mkdir -p "tmp/sysroot/state/${BASE_IMAGE_FSVERITY}/var"

${CFSCTL} oci prepare-boot "${FINAL_ID}" tmp/efi

../common/install-systemd-boot
../common/make-image "${os}-uki-efi.qcow2"
