#!/bin/sh

set -eux

cd "${0%/*}"

qemu-system-x86_64 \
    -m 4096 \
    -enable-kvm \
    -bios /usr/share/edk2/ovmf/OVMF_CODE.fd \
    -drive file=image.qcow2,if=virtio \
    -kernel /usr/lib/systemd/boot/efi/systemd-bootx64.efi
