#!/bin/sh

set -eux

os="${1:-fedora}"
cd "${0%/*}"

../common/check-config

if [ "${os}" != 'fedora' ]; then
    echo '*** only fedora is supported'
    false
fi

cargo build --release --features=pre-6.15

cp ../../target/release/cfsctl .
cp ../../target/release/composefs-setup-root extra/usr/lib/dracut/modules.d/37composefs/
CFSCTL='./cfsctl --repo tmp/sysroot/composefs'

rm -rf tmp
mkdir -p tmp/sysroot/composefs

# For debugging, add --no-cache to podman command
mkdir tmp/internal-sysroot
podman build \
    --iidfile=tmp/iid \
    -v "${PWD}/tmp/internal-sysroot:/tmp/sysroot:z,U" \
    .

IMAGE_ID="$(sed s/sha256:// tmp/iid)"
${CFSCTL} oci pull containers-storage:"${IMAGE_ID}"
IMAGE_FSVERITY="$(${CFSCTL} oci create-image "${IMAGE_ID}")"

mkdir -p "tmp/sysroot/state/${IMAGE_FSVERITY}/etc/work"
mkdir -p "tmp/sysroot/state/${IMAGE_FSVERITY}/etc/upper"
mkdir -p "tmp/sysroot/state/${IMAGE_FSVERITY}/var"

${CFSCTL} oci prepare-boot "${IMAGE_ID}" tmp/efi

../common/install-systemd-boot
../common/make-image fedora-unified-efi.qcow2
